require("poggy")
-- require("after.plugin.colorizer")
-- require("after.plugin.copilot")
-- require("after.plugin.fugitive")
-- require("after.plugin.harpoon")
-- require("after.plugin.nvimtree")
-- require("after.plugin.telescope")
-- require("after.plugin.treesitter")
-- require("after.plugin.undotree")
