modkey = "Mod4"
workspaces = []
tags = ["", "", "", "", "", "", "漣"]


## Layouts
layouts = [
    #"MainAndDeck",
    "MainAndVertStack",
    #"MainAndHorizontalStack",
    #"GridHorizontal",
    #"EvenHorizontal",
    #"EvenVertical",
    #"Fibonacci",
    #"CenterMain",
    "CenterMainBalanced",
    #"RightWiderLeftStack",
    #"LeftWiderRightStack",
    "Monocle",
]


## Window Focus
focus_behaviour = "Sloppy" # Can be Sloppy, ClickTo, or Driven
focus_new_windows = true


## Keybinds
keybind = [

  ## Format
  # { command = "", value = "", modifier = [], key = "" }

  { command = "CloseWindow", modifier = ["modkey"], key = "c" },

  ## Reload/Quit LeftWM
  { command = "SoftReload", modifier = ["Control", "Shift"], key = "r" },
  { command = "Execute", value = "pkill -KILL -u $USER", modifier = ["Control", "Shift"], key = "q" },

  { command = "IncreaseMainWidth", value = "5", modifier = ["modkey", "Shift"], key = "l" },
  { command = "DecreaseMainWidth", value = "5", modifier = ["modkey", "Shift"], key = "h" },

  { command = "FloatingToTile", modifier = ["modkey"], key = "t" },
  { command = "ToggleFullScreen", modifier = ["modkey"], key = "f" },

  { command = "MoveWindowUp", modifier = ["modkey", "Shift"], key = "Right" },
  { command = "MoveWindowDown", modifier = ["modkey", "Shift"], key = "Left" },

  { command = "FocusWindowUp", modifier = ["Control", "Shift"], key = "j" },
  { command = "FocusWindowDown", modifier = ["Control", "Shift"], key = "k" },

  ## Switch Layouts
  { command = "NextLayout", modifier = ["modkey", "Control"], key = "comma" },
  { command = "PreviousLayout", modifier = ["modkey", "Control"], key = "period" },

  ## Switch From Tag 1 to 7
  { command = "GotoTag", value = "1", modifier = ["modkey"], key = "1" },
  { command = "GotoTag", value = "2", modifier = ["modkey"], key = "2" },
  { command = "GotoTag", value = "3", modifier = ["modkey"], key = "3" },
  { command = "GotoTag", value = "4", modifier = ["modkey"], key = "4" },
  { command = "GotoTag", value = "5", modifier = ["modkey"], key = "5" },
  { command = "GotoTag", value = "6", modifier = ["modkey"], key = "6" },
  { command = "GotoTag", value = "7", modifier = ["modkey"], key = "7" },

  ## Move Windows From One Tag to Another
  { command = "MoveToTag", value = "1", modifier = ["modkey", "Shift"], key = "1" },
  { command = "MoveToTag", value = "2", modifier = ["modkey", "Shift"], key = "2" },
  { command = "MoveToTag", value = "3", modifier = ["modkey", "Shift"], key = "3" },
  { command = "MoveToTag", value = "4", modifier = ["modkey", "Shift"], key = "4" },
  { command = "MoveToTag", value = "5", modifier = ["modkey", "Shift"], key = "5" },
  { command = "MoveToTag", value = "6", modifier = ["modkey", "Shift"], key = "6" },
  { command = "MoveToTag", value = "7", modifier = ["modkey", "Shift"], key = "7" },
]

