local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>sf', builtin.find_files, {})
vim.keymap.set('n', ';;', builtin.find_files, {});
vim.keymap.set('n', '<leader>sw', builtin.live_grep, {})
vim.keymap.set('n', '<leader>sb', builtin.buffers, {})
vim.keymap.set('n', '<leader>sh', builtin.help_tags, {})
vim.keymap.set("n", "<C-p>", builtin.find_files, {})
vim.keymap.set('n', "<C-b>", builtin.buffers, {})
vim.keymap.set('n', "<C-f>", builtin.live_grep, {})
